# excample configuration file for trace player
client_info: # Required for run command
    threads: 1 #  number of layers pulled in parallel
    realblobs: # NANNAN: lst of real blobs
        - /home/nannan/dockerimages/layers/hulk1_layers_less_50m.lst

trace: # mandatory field
    location: /home/nannan/dockerimages/docker-traces/data_centers/dal09 # use a small trace for debugging
    traces:
        # - total_trace_dal09.json
        - prod-dal09-logstash-2017.06.20-1.json

    # entire trace used if limit not speciiied
    limit: 
        type: requests # seconds and requests are supported
        amount: 500

    output: results.json # only used in run mode, produced output trace with latencies

registry-helpers:
    port: 8082
    
redis:
    host: 192.168.0.220 #thor20
    port: 6379
    
registry:   
    - 192.168.0.170:5000
    - 192.168.0.171:5000
    - 192.168.0.172:5000
    - 192.168.0.174:5000
#    - 192.168.0.176:5000
#    - 192.168.0.177:5000
#    - 192.168.0.178:5000
#    - 192.168.0.179:5000
#    - 192.168.0.180:5000

warmup: # required for run and warmup mode
    output: interm-3-5.json # name of file that holds mapping between trace uri's and hashes
    threads: 10 # how many clients used to push/pull blobs to registry

simulate: # required for simulate mode
    name: cache.py #name of plugin file, should contain init function
    args: # argument dictionary to be passed into 
        cache_size: 8 # cache size in GB
