# excample configuration file for trace player
client_info: # Required for run command
    threads: 1 #  number of layers pulled in parallel
    realblobs: # NANNAN: lst of real blobs
        - /home/nannan/dockerimages/layers/hulk1/hulk1_layers_less_50m.lst
        #	- /home/nannan/dockerimages/layers/hulk1_layers_bigger_2g.lst
        #- /home/nannan/dockerimages/layers/hulk1/hulk1_layers_less_1g.lst
        #	- /home/nannan/dockerimages/layers/hulk1_layers_less_2g.lst
        #	- /home/nannan/dockerimages/layers/hulk4_layers_bigger_2g.lst
        #	- /home/nannan/dockerimages/layers/hulk4_layers_less_1g.lst
        #	- /home/nannan/dockerimages/layers/hulk4_layers_less_2g.lst
        #	- /home/nannan/dockerimages/layers/hulk4_layers_less_50m.lst

trace: # mandatory field
    location: /home/nannan/dockerimages/docker-traces/data_centers/ # use a small trace for debugging
    traces:
#        - prod-dal09-logstash-2017.06.20-0.json
#        - prod-dal09-logstash-2017.06.20-1.json
#        - prod-dal09-logstash-2017.06.20-2.json
#        - prod-dal09-logstash-2017.06.20-3.json
#        - prod-dal09-logstash-2017.06.21-0.json
#        - prod-dal09-logstash-2017.06.21-1.json
#        - prod-dal09-logstash-2017.06.21-2.json
#        - prod-dal09-logstash-2017.06.21-3.json
#        **********************************************
#         - dal09/prod-dal09-logstash-2017.06.20-0.json
#         ------------------------------------------------
#         - dev-mon01/dev-mon01-logstash-2017.07.13-0.json
#         - dev-mon01/dev-mon01-logstash-2017.07.13-1.json  
#         - dev-mon01/dev-mon01-logstash-2017.07.13-2.json
#         - dev-mon01/dev-mon01-logstash-2017.07.13-3.json 
#         - dev-mon01/dev-mon01-logstash-2017.07.14-0.json  
#         - dev-mon01/dev-mon01-logstash-2017.07.14-1.json  
#         - dev-mon01/dev-mon01-logstash-2017.07.14-2.json
#         - dev-mon01/dev-mon01-logstash-2017.07.14-3.json 
#         - dev-mon01/dev-mon01-logstash-2017.07.15-0.json
#         - dev-mon01/dev-mon01-logstash-2017.07.15-1.json
#         -------------------------------------------------  
#          - fra02/prod-fra02-logstash-2017.06.20-0.json
#          - fra02/prod-fra02-logstash-2017.06.20-1.json
#          - fra02/prod-fra02-logstash-2017.06.20-3.json
#          - fra02/prod-fra02-logstash-2017.06.21-0.json
#          - fra02/prod-fra02-logstash-2017.06.21-1.json
#          - fra02/prod-fra02-logstash-2017.06.21-2.json
#          - fra02/prod-fra02-logstash-2017.06.21-3.json
#          - fra02/prod-fra02-logstash-2017.06.22-0.json
#          - fra02/prod-fra02-logstash-2017.06.22-1.json
#          - fra02/prod-fra02-logstash-2017.06.22-2.json
#          - fra02/prod-fra02-logstash-2017.06.22-3.json
#          -------------------------------------------------------
#          - lon02/prod-lon02-logstash-2017.06.20-0.json
#         ------------------------------------------------
#          - prestage-mon01/prestage-mon01-logstash-2017.07.03-0.json
#          - prestage-mon01/prestage-mon01-logstash-2017.07.03-1.json
#          - prestage-mon01/prestage-mon01-logstash-2017.07.03-2.json
#          - prestage-mon01/prestage-mon01-logstash-2017.07.03-3.json
#          - prestage-mon01/prestage-mon01-logstash-2017.07.04-0.json
#          - prestage-mon01/prestage-mon01-logstash-2017.07.04-1.json
#          - prestage-mon01/prestage-mon01-logstash-2017.07.04-2.json
#          - prestage-mon01/prestage-mon01-logstash-2017.07.04-3.json
#          ----------------------------------------------------------
#          - stage-dal09/stage-dal09-logstash-2017.06.27-0.json
#          ---------------------------------------------------------
          - syd01/prod-syd01-logstash-2017.07.01-0.json  
          - syd01/prod-syd01-logstash-2017.07.01-1.json
          - syd01/prod-syd01-logstash-2017.07.01-2.json
          - syd01/prod-syd01-logstash-2017.07.01-3.json
          - syd01/prod-syd01-logstash-2017.07.02-0.json
          - syd01/prod-syd01-logstash-2017.07.02-1.json
          - syd01/prod-syd01-logstash-2017.07.02-2.json
          - syd01/prod-syd01-logstash-2017.07.02-3.json
    
    limit: # entire trace used if limit not speciiied
        amount: 5000

    output: results.json # only used in run mode, produced output trace with latencies
 
registry:   
#    - 192.168.0.170:5000
#    - 192.168.0.171:5000
#    - 192.168.0.172:5000
#    - 192.168.0.174:5000
#    - 192.168.0.176:5000
#    - 192.168.0.177:5000
#    - 192.168.0.179:5000
#    - 192.168.0.180:5000
    - 192.168.0.200:5000           
    - 192.168.0.201:5000           
    - 192.168.0.202:5000           
    - 192.168.0.203:5000           
    - 192.168.0.204:5000           
    - 192.168.0.205:5000                     
    - 192.168.0.208:5000           
    - 192.168.0.209:5000           
    - 192.168.0.210:5000           
    - 192.168.0.211:5000           
    - 192.168.0.212:5000           
    - 192.168.0.213:5000           
    - 192.168.0.214:5000           
    - 192.168.0.215:5000           
    - 192.168.0.216:5000           
    - 192.168.0.217:5000           
    - 192.168.0.218:5000           
    - 192.168.0.219:5000                    
    - 192.168.0.221:5000           
    - 192.168.0.222:5000           
    - 192.168.0.223:5000

warmup: # required for run and warmup mode
    output: warmup_output.json # name of file that holds mapping between trace uri's and hashes
    threads: 100 #00 # how many clients used to push/pull blobs to registry

testmode: # required for simulate mode
    nodedup: True # nnzhaocs/distribution:original  
    sift: False # nnzhaocs/distribution:distributioncache

simulate:
    wait: True  #True # or no delay
#    getonly: False
    gettype: layer
    accelerater: 60
#    tracetype: first1tracefile # durationday #topnclients # first1tracefile
    
