
# excample configuration file for trace player
client_info: # Required for run command
    threads: 1 #  number of layers pulled in parallel
    realblobs: # NANNAN: lst of real blobs
        - /home/nannan/dockerimages/layers/hulk1/hulk1_layers_less_50m.lst
        #- /home/nannan/dockerimages/layers/hulk1/hulk_layers_approx_1MB.lst  
        #- /home/nannan/dockerimages/layers/hulk1/hulk_layers_approx_5MB.lst
        #- /home/nannan/dockerimages/layers/hulk1/hulk_layers_approx_10MB.lst
          #- /home/nannan/dockerimages/layers/hulk1/hulk_layers_approx_20MB.lst
          #- /home/nannan/dockerimages/layers/hulk1/hulk_layers_approx_30MB.lst
          #- /home/nannan/dockerimages/layers/hulk1/hulk_layers_approx_40MB.lst
          #- /home/nannan/dockerimages/layers/hulk1/hulk_layers_approx_50MB.lst
          #- /home/nannan/dockerimages/layers/hulk1/hulk_layers_approx_60MB.lst
        #	- /home/nannan/dockerimages/layers/hulk1_layers_bigger_2g.lst
        #- /home/nannan/dockerimages/layers/hulk1/hulk1_layers_less_1g.lst
        #	- /home/nannan/dockerimages/layers/hulk1_layers_less_2g.lst
        #	- /home/nannan/dockerimages/layers/hulk4_layers_bigger_2g.lst
        #	- /home/nannan/dockerimages/layers/hulk4_layers_less_1g.lst
        #	- /home/nannan/dockerimages/layers/hulk4_layers_less_2g.lst
        #	- /home/nannan/dockerimages/layers/hulk4_layers_less_50m.lst

trace: # mandatory field
    location: /home/nannan/dockerimages/docker-traces/data_centers #/dal09 # use a small trace for debugging
    traces:
#        - dal09_total_trace.json
#        - dev-mon01_total_trace.json
#        - fra02_total_trace.json
#        - lon02_total_trace.json
#        - prestage-mon01_total_trace.json
#        - stage-dal-09_total_trace.json
#        - syd01_total_trace.json
#        **********************************************
         - dal09/prod-dal09-logstash-2017.06.20-0.json
#         ------------------------------------------------
#         - dev-mon01/dev-mon01-logstash-2017.07.13-0.json
#         - dev-mon01/dev-mon01-logstash-2017.07.13-1.json  
#         - dev-mon01/dev-mon01-logstash-2017.07.13-2.json
#         - dev-mon01/dev-mon01-logstash-2017.07.13-3.json 
#         - dev-mon01/dev-mon01-logstash-2017.07.14-0.json  
#         - dev-mon01/dev-mon01-logstash-2017.07.14-1.json  
#         - dev-mon01/dev-mon01-logstash-2017.07.14-2.json
#         - dev-mon01/dev-mon01-logstash-2017.07.14-3.json 
#         - dev-mon01/dev-mon01-logstash-2017.07.15-0.json
#         - dev-mon01/dev-mon01-logstash-2017.07.15-1.json
#         -------------------------------------------------  
#          - fra02/prod-fra02-logstash-2017.06.20-0.json
#          - fra02/prod-fra02-logstash-2017.06.20-1.json
#          - fra02/prod-fra02-logstash-2017.06.20-3.json
#          - fra02/prod-fra02-logstash-2017.06.21-0.json
#          - fra02/prod-fra02-logstash-2017.06.21-1.json
#          - fra02/prod-fra02-logstash-2017.06.21-2.json
#          - fra02/prod-fra02-logstash-2017.06.21-3.json
#          - fra02/prod-fra02-logstash-2017.06.22-0.json
#          - fra02/prod-fra02-logstash-2017.06.22-1.json
#          - fra02/prod-fra02-logstash-2017.06.22-2.json
#          - fra02/prod-fra02-logstash-2017.06.22-3.json
#          -------------------------------------------------------
#          - lon02/prod-lon02-logstash-2017.06.20-0.json
#         ------------------------------------------------
#          - prestage-mon01/prestage-mon01-logstash-2017.07.03-0.json
#          - prestage-mon01/prestage-mon01-logstash-2017.07.03-1.json
#          - prestage-mon01/prestage-mon01-logstash-2017.07.03-2.json
#          - prestage-mon01/prestage-mon01-logstash-2017.07.03-3.json
#          - prestage-mon01/prestage-mon01-logstash-2017.07.04-0.json
#          - prestage-mon01/prestage-mon01-logstash-2017.07.04-1.json
#          - prestage-mon01/prestage-mon01-logstash-2017.07.04-2.json
#          - prestage-mon01/prestage-mon01-logstash-2017.07.04-3.json
#          ----------------------------------------------------------
#          - stage-dal09/stage-dal09-logstash-2017.06.27-0.json
#          ---------------------------------------------------------
#          - syd01/prod-syd01-logstash-2017.07.01-0.json  
#          - syd01/prod-syd01-logstash-2017.07.01-1.json
#          - syd01/prod-syd01-logstash-2017.07.01-2.json
#          - syd01/prod-syd01-logstash-2017.07.01-3.json
#          - syd01/prod-syd01-logstash-2017.07.02-0.json
#          - syd01/prod-syd01-logstash-2017.07.02-1.json
#          - syd01/prod-syd01-logstash-2017.07.02-2.json
#          - syd01/prod-syd01-logstash-2017.07.02-3.json
    
    limit: # entire trace used if limit not speciiied
        amount: 100

    output: results.json # only used in run mode, produced output trace with latencies
 
primaryregistry:   
        #    - 192.168.0.170:5000
        #    - 192.168.0.171:5000
        #    - 192.168.0.172:5000
        #    - 192.168.0.174:5000
#    - 192.168.0.176:5000
#    - 192.168.0.177:5000
#    - 192.168.0.179:5000
#    - 192.168.0.180:5000
#    - 192.168.0.200:5000           
#    - 192.168.0.201:5000           
#    - 192.168.0.202:5000           
#    - 192.168.0.203:5000           
#    - 192.168.0.204:5000           
#    - 192.168.0.205:5000                     
#    - 192.168.0.208:5000           
#    - 192.168.0.209:5000           
#    - 192.168.0.210:5000           
#    - 192.168.0.211:5000           
#    - 192.168.0.212:5000           
    - 192.168.0.213:5000           
    - 192.168.0.214:5000           
    - 192.168.0.215:5000           
    - 192.168.0.216:5000           
    - 192.168.0.217:5000           
    - 192.168.0.218:5000           
    - 192.168.0.219:5000                    
    - 192.168.0.221:5000           
    - 192.168.0.222:5000           
    - 192.168.0.223:5000

dedupregistry:   
#    - 192.168.0.170:5000
#    - 192.168.0.171:5000
#    - 192.168.0.172:5000
#    - 192.168.0.174:5000
      #    - 192.168.0.176:5000
      #    - 192.168.0.177:5000
      #    - 192.168.0.179:5000
      #    - 192.168.0.180:5000
    - 192.168.0.200:5000           
    - 192.168.0.201:5000           
    - 192.168.0.202:5000           
    - 192.168.0.203:5000           
    - 192.168.0.204:5000           
    - 192.168.0.205:5000                     
    - 192.168.0.208:5000           
    - 192.168.0.209:5000           
    - 192.168.0.210:5000           
    - 192.168.0.211:5000           
    - 192.168.0.212:5000           
#    - 192.168.0.213:5000           
#    - 192.168.0.214:5000           
#    - 192.168.0.215:5000           
#    - 192.168.0.216:5000           
#    - 192.168.0.217:5000           
#    - 192.168.0.218:5000           
#    - 192.168.0.219:5000                    
#    - 192.168.0.221:5000           
#    - 192.168.0.222:5000           
#    - 192.168.0.223:5000

clients:
    - 192.168.0.151
    - 192.168.0.152
    - 192.168.0.153
    - 192.168.0.154
    - 192.168.0.156
          
warmup: # required for run and warmup mode
    output: warmup_output.json # name of file that holds mapping between trace uri's and hashes
    threads: 20 #00 # how many clients used to push/pull blobs to registry

testmode: # required for simulate mode
    nodedup: False # nnzhaocs/distribution:original  
    sift: True #False #False #True  # nnzhaocs/distribution:distributioncache
            #nnzhaocs/distribution:distributionthors0-12
    restore: False

siftparams:  
    mode: selective
    selective: 
        hotratio: 0.25 # 0.1 
    standard: 
        nondedupreplicas: 2             

simulate:
    wait: True  #True # or no delay
#    getonly: False
#    gettype: layer
    accelerater: 12
#    tracetype: first1tracefile # durationday #topnclients # first1tracefile
#    biglayer: True
    replicalevel: 3
biglayers:    
#    location: /home/nannan/dockerimages/layers/hulk1/splited_layers  #/dal09 # use a small trace for debugging
    traces: /home/nannan/dockerimages/layers/hulk1/hulk1_layers_less_1g_splits.lst   
    number: 2
    max: 4000
 
